[
   NbsCount                     -- KW["#("] _1 KW[")"],
   Nbs                          -- KW["$("] _1 KW[")"],
   NbsOp                        -- _1 KW[","] _2,
   NbsOp.2:iter-sep             -- _1 KW[","],
   NbsOp                        -- _1,
   ConnFilter                   -- _1,
   ConnFilter                   -- _1 KW["->"] _2,
   metaPart                     -- KW["module.metaPart"] KW["=="] _1,
   connected                    -- KW["connected"] KW[":"] _1,
   inRegion                     -- KW["inRegion"] KW[":"] _1,
   withMetaID                   -- KW["module.metaID"] KW["=="] _1,
   connDest                     -- KW["connDest"] KW[":"] _1,
   connSource                   -- KW["connSource"] KW[":"] _1,
   in                           -- _1,
   MetaPart                     -- _1,
   Int                          -- _1,
   Const                        -- _1,
   Bool                         -- _1,
   ModHolder                    -- _1,
   Par                          -- KW["("] _1 KW[")"],
   ByteArr                      -- KW["["] _1 KW["]"],
   ByteArr.1:iter-star-sep      -- _1 KW[","],
   String                       -- _1,
   Mod                          -- _1 KW["%"] _2,
   Not                          -- KW["!"] _1,
   Min                          -- KW["-"] _1,
   Min                          -- _1 KW["-"] _2,
   Mul                          -- _1 KW["*"] _2,
   Div                          -- _1 KW["/"] _2,
   Plus                         -- _1 KW["+"] _2,
   Min                          -- _1 KW["-"] _2,
   Lt                           -- _1 KW["<"] _2,
   Gt                           -- _1 KW[">"] _2,
   LtEq                         -- _1 KW["<="] _2,
   GtEq                         -- _1 KW[">="] _2,
   Eq                           -- _1 KW["=="] _2,
   Neq                          -- _1 KW["!="] _2,
   And                          -- _1 KW["&&"] _2,
   Or                           -- _1 KW["||"] _2,
   AndBit                       -- _1 KW["&"] _2,
   OrBit                        -- _1 KW["|"] _2,
   Start                        -- _1 _2 _3,
   Start.2:iter-star            -- _1,
   Start.3:iter-star            -- _1,
   Module                       -- KW["module"] _1,
   MetaNS                       -- KW["meta"] KW["{"] _1 _2 _3 KW["}"],
   MetaNS.1:iter-star           -- _1,
   MetaNS.2:iter-star           -- _1,
   MetaNS.3:iter-star           -- _1,
   ModuleNS                     -- KW["module"] KW["{"] _1 _2 KW["}"],
   ModuleNS.1:iter-star         -- _1,
   ModuleNS.2:iter-star         -- _1,
   FuncDecl                     -- KW["void"] _1 KW["("] _2 KW[")"] KW["{"] _3 _4 KW["}"],
   FuncDecl.2:iter-star-sep     -- _1 KW[","],
   FuncDecl.3:iter-star         -- _1,
   FuncDecl.4:iter-star         -- _1,
   FuncDecl                     -- _1 _2 KW["("] _3 KW[")"] KW["{"] _4 _5 KW["return"] _6 KW[";"] KW["}"],
   FuncDecl.3:iter-star-sep     -- _1 KW[","],
   FuncDecl.4:iter-star         -- _1,
   FuncDecl.5:iter-star         -- _1,
   Elem                         -- _1 _2,
   Packet                       -- KW["packet"] _1 KW["{"] _2 KW["}"],
   Packet.2:iter-star           -- _1,
   VarDecl                      -- _1 _2 KW[";"],
   VarDecl.2:iter-sep           -- _1 KW[","],
   MetaPartDecl                 -- KW["part"] KW["["] _1 KW["]"] KW[";"],
   MetaPartDecl.1:iter-star-sep -- _1 KW[","],
   VarRef                       -- _1,
   FieldRef                     -- _1 KW["."] _2,
   FieldRef                     -- _1 KW["."] _2,
   Assign                       -- _1 KW["="] _2,
   AssignList                   -- _1,
   AssignList.1:iter-star-sep   -- _1 KW[","],
   State                        -- KW["state"] _1 KW["{"] _2 _3 _4 KW["}"],
   State.2:iter-star            -- _1,
   State.3:iter-star            -- _1,
   State.4:iter-star            -- _1,
   EvHdlr                       -- KW["when"] KW["("] _1 KW[")"] KW["{"] _2 _3 KW["}"],
   EvHdlr.2:iter-star           -- _1,
   EvHdlr.3:iter-star           -- _1,
   Event                        -- KW["receive"] KW["("] _1 _2 KW[")"],
   Event                        -- _1,
   Rate                         -- KW["rate"] _1,
   Unicast                      -- KW["unicast"] _1 KW["("] _2 KW[")"] KW["on"] _3 _4 KW[";"],
   Unicast.4:opt                -- _1,
   Broadcast                    -- KW["broadcast"] _1 KW["("] _2 KW[")"] _3 KW[";"],
   Broadcast.3:opt              -- _1,
   Assign                       -- _1 KW["="] _2 KW[";"],
   FuncCall                     -- _1 KW["("] _2 KW[")"],
   FuncCall.2:iter-star-sep     -- _1 KW[","],
   FuncCall                     -- _1 KW["("] _2 KW[")"] KW[";"],
   FuncCall.2:iter-star-sep     -- _1 KW[","],
   FuncCall                     -- _1 KW["."] _2 KW["("] _3 KW[")"] KW[";"],
   FuncCall.3:iter-star-sep     -- _1 KW[","],
   FuncCall                     -- _1 KW["."] _2 KW["("] _3 KW[")"],
   FuncCall.3:iter-star-sep     -- _1 KW[","],
   Stmt                         -- V  [V vs=2 [KW["{"] _1] KW["}"]],
   Stmt.1:iter-star             -- _1,
   IfElse                       -- KW["if"] KW["("] _1 KW[")"] _2 KW["else"] _3,
   If                           -- KW["if"] KW["("] _1 KW[")"] _2,
   Goto                         -- KW["goto"] _1 KW[";"],
   Goto                         -- KW["goto"] _1 KW["orientating"] _2 KW[";"],
   Group                        -- KW["group"] _1 KW["["] _2 KW["]"] KW[";"],
   Group.2:iter-star-sep        -- _1 KW[","],
   GroupMum                     -- KW["group"] _1 KW[";"],
   Disconnect                   -- KW["disconnect"] KW["("] _1 KW[","] _2 KW[")"] KW[";"],
   Connect                      -- KW["connect"] KW["("] _1 KW[","] _2 KW[")"] KW[";"],
   Rotate                       -- KW["rotate"] KW["("] _1 KW[","] _2 KW[")"] KW[";"],
   RotateCont                   -- KW["rotate_continuous"] KW["("] _1 KW[","] _2 KW[")"] KW[";"],
   Stop                         -- KW["stop"] KW["("] _1 KW[")"] KW[";"],
   For                          -- KW["for"] KW["("] _1 _2 KW[":"] _3 KW[")"] KW["{"] _4 KW["}"],
   Send                         -- KW["send"] _1 KW["("] _2 KW[")"] KW["to"] _3 KW[";"],
   Send.2:iter-star-sep         -- _1 KW[","],
   Wait                         -- KW["wait"],
   Until                        -- KW["until"]
]